/*
 * Port_Config.h
 *
 *  Created on: Nov 23, 2019
 *      Author: AhmedShawky
 */

#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_
#include "Port_Priv.h"


#define NUM_OF_GROUPS                 6
#define SUBPRIORITY_STATUS            DISABELED

//THE SUBPRIORITY LEVELS NUMBER GOES FROM 1 TO 8,IT'S EITHER 1,2,4 OR 8
#define SUBPRIORITY_LEVEL_NUM             1


//THE GROUP PRIORITY IS FROM 0 T0 7 ,IF 2 PORTS HAVE THE SAME GP PRIORITIES AND BOTH ARE PENDING WE LOOK AT THE SUBPRIORITIES
//WHILE IF BOTH HAVE THE SAME GP PRIORITY THEY CAN NOT INTERRUPT EACH OTHER EVEN IF ONE HAVE A HIGHER SUB PRIORITY


//PLEASE TAKE INTO CONSIDERATION THAT WHEN USING THE SUBPRIOITY_LEVEL_NUM AS 1 YOU DO USE THE FULL 3-BITS OF THE GP_PRI NUMBER ASSIGNED
//WHILE WHEN CHOOSING THE SUBPRIOITY_LEVEL_NUM AS 2 YOU TAKE THE HIGHEST 2 BITS AS GP_PRI AND THE LEAST AS THE SUB_PRI
//WHEN CHOOSING 4 YOU TAKE THE LOWEST 2 AS SUB_PRI AND THE HIGHEST AS GP_PRI





#endif /* PORT_CONFIG_H_ */
